# version: '3.8'

services:
  wordpress:
    image: wordpress:latest
    container_name: wordpress
    depends_on:
      - db
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_DB_NAME: wordpress
    ports:
      - "${WORDPRESS_PORT}:80"
    volumes:
      - wordpress_data:/var/www/html
    restart: always
    networks:
      - wpnet

  db:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: wordpress
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    networks:
      - wpnet

volumes:
  wordpress_data:
  db_data:

networks:
  wpnet:
    driver: bridge