services:
  wordpress:
    image: wordpress:latest
    container_name: wordpress
    depends_on:
      - db
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_DB_NAME: wordpress
    ports:
      - "${WORDPRESS_HTTPS_PORT}:443"  # HTTPS manejado por variable de entorno
      - "${WORDPRESS_HTTP_PORT}:80"   # HTTP manejado por variable de entorno
    volumes:
      - wordpress_data:/var/www/html
    restart: always
    networks:
      - wpnet